FROM node:16.13.2-alpine as builder

WORKDIR /workspace
COPY . .
RUN yarn --frozen-lockfile && yarn build

FROM node:16.13.2-alpine
WORKDIR /workspace
COPY --from=builder /workspace/.next ./
RUN yarn --frozen-lockfile --production

ENV NODE_ENV production
EXPOSE 3000

CMD ["next", "start"]
