# Must be standalone mode

FROM node:16.13.2-alpine as builder

WORKDIR /workspace
COPY . .
RUN yarn --frozen-lockfile && yarn build &&\
  cp -r -u .next/server .next/standalone/.next &&\
  cp -r -u .next/static .next/standalone/.next &&\
  cp -r -u public .next/standalone

FROM node:16.13.2-alpine
WORKDIR /workspace
COPY --from=builder /workspace/.next/standalone ./

ENV NODE_ENV production
EXPOSE 3000

CMD ["node", "server.js"]
